### ISSUE TITLE
At build time, should warn user if they impement a relation which does not have code

### ISSUE THREAD

**Issue by marcoceppi** [juju/charm-tools#105]
There are several impartial implementations of an interface in the interface site.

If a user has the following:

```yaml
provides:
  relation:
    interface: you-knows-it
```

and `interface:you-knows-it` only has a `requires.py` then the user should be faced with a WARNING or potentially ERROR that the relation will not be implemented properly.
