### ISSUE TITLE
charm-build should error if defining options for a non-existant layer

### ISSUE THREAD

**Issue by chuckbutler** [juju/charm-tools#173]
When defining layer options according to JSON Schema, such as the following [link describes](http://spacetelescope.github.io/understanding-json-schema/reference/generic.html): i would expect any inheriting layer, that defines an option that doesn't exist in the list to error during  `charm build`

Given in the base layer:

```yaml
defines:
  storage-driver:
    enum: [overlay, aufs, btrfs, zfs]
    default: aufs
    description: |
      Used in conjunction with the storage volume in metadata.yaml.
      Supported providers, when prompted, will allow you to mount a block
      device, formatted for use with the storage driver configured here.
```

And in the inheriting layer:

```yaml
options:
  storage-driver:
    value: schenanigans
```

I expected during the build time, the base schema to be validated. ENUM type should have limited the values to those defined as valid: 'aufs', 'btrfs', 'zfs', or 'overlay' - anything outside of this pre-defined list when provided as a value should have actively prevented the build, or failed it, as it doesn't validate against the defined schema.

**Comment by chuckbutler** [comment]
It appears I input the options wrong which raises a different issue. The layers options are not validating if we are even targeting an existing layer being used during hte build process. 

the inheriting layer should have apppeared as the following:

```yaml
options:
  docker:
    storage-driver: schenanigans
```

And the providing layer to trigger was updated to:

```yaml
  storage-driver:
    type: string
    enum: ['overlay', 'aufs', 'btrfs', 'zfs']
    default: aufs
    description: |
      Used in conjunction with the storage volume in metadata.yaml.
      Supported providers, when prompted, will allow you to mount a block
      device, formatted for use with the storage driver configured here.
```

The resulting output:

```
charmtools.build.tactics: Invalid value for option docker.storage-driver: 'poop' is not one of ['overlay', 'aufs', 'btrfs', 'zfs']
```
