### ISSUE TITLE
The metadata tactic needs de-duplication

### ISSUE THREAD

**Issue by mbruzek** [juju/charm-tools#186]
I built a charm from several layers and I see all the maintainers are in the resulting `metadata.yaml` file. Some of this is our fault, we spelled our names or emails differently, but the names that are exactly the same should be de-duplicated.

```yaml
"name": "kubernetes"
"summary": "Kubernetes is an application container orchestration platform."
"description": |
  Kubernetes is an open-source platform for deplying, scaling, and operations
  of appliation containers across a cluster of hosts. Kubernetes is portable
  in that it works with public, private, and hybrid clouds. Extensible through
  a pluggable infrastructure. Self healing in that it will automatically
  restart and place containers on healthy nodes if a node ever goes away.
"tags":
- "containers"
- "layer"
- "containers"
- "networking"
- "infrastructure"
- "security"
- "infrastructure"
"requires":
  "etcd":
    "interface": "etcd"
"provides":
  "dockerhost":
    "interface": "dockerhost"
    "scope": "container"
"peers":
  "certificates":
    "interface": "tls"
"maintainers":
- "Charles Butler <charles.butler@canonical.com>"
- "Matt Bruzek <matthew.bruzek@canonical.com>"
- "Charles Butler <charles.butler@canonical.com>"
- "Matthew Bruzek <matthew.bruzek@ubuntu.com>"
- "Matthew Bruzek <matthew.bruzek@canonical.com>"
- "Charles Butler <charles.butler@canonical.com>"
"subordinate": !!bool "false"
```
The **maintainer** and the **tags** values could be de-duplicated. This could be done by casting them to a set or using a loop to detect if a value has already been written by another method.
