### ISSUE TITLE
proof needs to support metadata.yaml `terms` key

### ISSUE THREAD

**Issue by AdamIsrael** [juju/charm-tools#190]
`charm proof` needs to recognize the metadata key `term`:

```yaml
name: terms1
summary: "That's a dummy charm with terms."
description: |
    This is a longer description which
    potentially contains multiple lines.
terms: ["lorem-ipsum/1"]
```
