### ISSUE TITLE
'charm create' produces metadata.yaml that error with 'charm proof'

### ISSUE THREAD

**Issue by erik78se** [juju/charm-tools#505]
* Used: charm create, charm proof
* Version of charm: 2.5.2

## What version am I running?
```
snap info charm
name:      charm
summary:   charm and charm-tools
publisher: Cory Johns (johnsca)
contact:   juju@lists.ubuntu.com
license:   unset
description: |
  charmstore-client and charm-tools
commands:
  - charm
snap-id:      2Rryoc2ylScfbFl4eQtpntHD9iuZuMvt
tracking:     stable
refresh-date: 23 days ago, at 17:26 CET
channels:
  stable:    2.5.2                2019-02-07 (320) 47MB classic
  candidate: 2.5.2                2019-02-07 (320) 47MB classic
  beta:      2.5.2                2019-02-07 (320) 47MB classic
  edge:      2.5.2+git-3-gef3d9a6 2019-02-12 (326) 47MB classic
installed:   2.5.2                           (320) 47MB classic
```

I am using:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

## Issue
I create a new charm with:
```bash
charm create -t bash hookmissingcharm"
```

My intention is to have NO interfaces / relations for this charm. E.g. no provides, requires or peers sections in metadata.yaml

When I try to figure out if the charm is OK or not with charm proof, it will indicate that this charm has problems. Messages that makes no sense at to me and provides no hints on whats actually going on:
```
$ charm proof
I: `display-name` not provided, add for custom naming in the UI
I: Includes template icon.svg file.
W: no copyright file
E: template interface names should be changed: interface-name
I: relation provides-relation has no hooks
E: template interface names should be changed: interface-name
I: relation requires-relation has no hooks
E: template interface names should be changed: interface-name
I: relation peer-relation has no hooks
```

### I expected the following
* The 'charm proof' produce better help or indication on whats wrong with the situation if my charm has no relations/interfaces defined in metadata.yaml.

* The generated metadata.yaml is populated with information that the relations may be removed if not used. Something like this (metadata.yaml).
```
name: hookmissingcharm
summary: foo
maintainer: Erik Lnroth <Erik.Lnroth@juju-dev>
description: |
  <Multi-line description here>
tags:
  # Replace "misc" with one or more whitelisted tags from this list:
  # https://jujucharms.com/docs/stable/authors-charm-metadata
  - misc

# Remove below this line if your charm isn't going to relate to anything.
subordinate: false
provides:
  provides-relation:
    interface: interface-name
requires:
  requires-relation:
    interface: interface-name
peers:
  peer-relation:
    interface: interface-name
```

### What I got
$ charm proof
```
I: `display-name` not provided, add for custom naming in the UI
I: Includes template icon.svg file.
W: no copyright file
E: template interface names should be changed: interface-name
I: relation provides-relation has no hooks
E: template interface names should be changed: interface-name
I: relation requires-relation has no hooks
E: template interface names should be changed: interface-name
I: relation peer-relation has no hooks
```
