### ISSUE TITLE
charm proof not aware of `payloads` metadata field

### ISSUE THREAD

**Issue by chuckbutler** [juju/charm-tools#93]
Payloads were added as of juju 1.25.0

```
payloads:
  application:
    type: docker
  database:
    type: kvm
```

When proofing a charm, these fields result in:

`E: Unknown root metadata field (payloads)`
