### ISSUE TITLE
charm build on yaml needs to do proper type casting

### ISSUE THREAD

**Issue by marcoceppi** [juju/charm-tools#99]
When you have a `config.yaml` with the following:

```yaml
options:
  install_keys:
    type: string
    description: The key for the Debian package repository.
    default: "01182252"
```

Because this is actually a string but /may/ be a string of INTs Yaml parses this to an integer, writes the built YAML as:

```yaml
options:
  install_keys:
    type: string
    description: The key for the Debian package repository.
    default: 01182252
```

When writing the YAML back out, charm build should typecast based on `type` of the config options (string, int, bool)

To test, check out @srbaker [neo4j layer](https://github.com/srbaker/neo4j-charm)
